export enum ResponseCode {
  // HTTP status
  HTTP_SUCCESS = 200,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  TOO_MANY_REQUESTS = 429,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,

  // custom response code
  SUCCESS = 0,
  UNKNOWN_ERROR = 4000,
  DB_QUERY_ERROR,
  OPTIONS_MISSED,
  LOGIN_REJECT,
  ILLEGAL_PARAMS,
  SESSION_REGENERATE_ERROR,
  SESSION_DESTROY_ERROR,
  CAPTCHA_INPUT_ERROR,

  // post: 80xx
  POST_NOT_FOUND = 8000,
  POST_SAVE_ERROR,
  POST_DELETE_ERROR,
  POST_COMMENT_CLOSED,
  POST_TYPE_INVALID,
  POST_GUID_CONFLICT,
  POST_TAXONOMY_MISSED,
  COPYRIGHT_ILLEGAL,

  // taxonomy: 81xx
  TAXONOMY_NOT_FOUND = 8100,
  TAXONOMY_INVISIBLE,
  TAXONOMY_QUERY_ERROR,
  TAXONOMY_SLUG_DUPLICATE,
  TAXONOMY_REMOVE_ERROR,
  TAXONOMY_TYPE_INVALID,
  TAXONOMY_STATUS_INVALID,
  TAXONOMY_SAVE_ERROR,
  TAXONOMY_DELETE_ERROR,

  // comment: 82xx
  COMMENT_SAVE_ERROR = 8200,

  // link: 83xx
  LINK_SAVE_ERROR = 8300,
  LINK_DELETE_ERROR,
  LINK_NOT_FOUND,

  // form: 84xx
  FORM_INPUT_ERROR = 8400,
  UPLOAD_ERROR,
  UPLOAD_PATH_CONFLICT,

  // user: 85xx
  USER_NOT_FOUND = 8500,

  // option: 86xx
  OPTION_SAVE_ERROR = 8600,

  // book: 88xx
  BOOK_SAVE_ERROR = 8800,

  // other
  VOTE_FAILURE = 8900,
  CAPTCHA_GENERATE_ERROR
}
